# Generated by Django 4.2.4 on 2023-09-02 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appte', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Item',
            new_name='Produto',
        ),
    ]
