# Generated by Django 4.2.4 on 2023-09-02 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appte', '0003_carrinhoitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrinhoitem',
            name='usuario',
        ),
    ]
